name: SkyRankUP
version: @version@
main: com.github.skylinx.skyrankup.SkyRankUP
api-version: 1.8
authors: [ SkyLinx ]
depend:
  - Vault
description: Simple RankUP plugin.
website: https://github.com/SkyLinx
